version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  connect-gce:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
      - gcp-cli/initialize
      - add_ssh_keys:
          fingerprints:
            - "13:6a:3d:36:89:7b:6b:b3:c6:18:68:1d:4a:5f:55:32"
      - run:
          name: check
          command: |
            gcloud auth list
#       - run:
#           name: check known hosts
#           command: |
#             cat ~/.ssh/known_hosts
      - run:
          name: SSH
          command: |
            gcloud compute ssh --zone "${GOOGLE_COMPUTE_ZONE}" "test-circleci"  --project "${GOOGLE_PROJECT_ID}" --ssh-key-file=~/.ssh/id_rsa_136a3d36897b6bb3c618681d4a5f5532 --command="bash -s" \<<EOF
              whoami
              ls -laH
            EOF
workflows:
  main:
    jobs:
      - connect-gce
