version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  connect-gce:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
      - gcp-cli/initialize
      - add_ssh_keys:
          fingerprints:
            - "10:4c:19:2f:aa:47:b4:ea:72:c1:58:08:61:64:0c:5d"
      - run:
          name: check
          command: |
            gcloud auth list
      - run:
          name: check keys
          command: |
            ls -laH ~/.ssh/
      - run:
          name: generate public key from SSH key
          command: |
            ssh-keygen -f ~/.ssh/id_rsa_104c192faa47b4ea72c1580861640c5d -y > ~/.ssh/id_rsa_104c192faa47b4ea72c1580861640c5d.pub
      - run:
          name: SSH
          command: |
            gcloud compute ssh --zone "${GOOGLE_COMPUTE_ZONE}" kelvintaywl@test-circleci  --project "${GOOGLE_PROJECT_ID}" --ssh-key-file=~/.ssh/id_rsa_104c192faa47b4ea72c1580861640c5d --ssh-flag="-v" --command="bash -s -o pipefail" <<EOF
              whoami
              ls -laH
              echo "$(whoami) was here!" > hello.txt
            EOF
workflows:
  main:
    jobs:
      - connect-gce
