version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  connect-gce:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: check
          command: |
            gcloud auth list
      - run:
          name: SSH
          command: |
            gcloud compute ssh --zone "${GOOGLE_COMPUTE_ZONE}" "test-circleci"  --project "${GOOGLE_PROJECT_ID}" --command="bash -s" \<<EOF
              whoami
              ls -laH
            EOF
workflows:
  main:
    jobs:
      - connect-gce
